DROP DATABASE IF EXISTS CH12_FETCHING;
CREATE DATABASE CH12_FETCHING;

DROP DATABASE IF EXISTS CH12_FETCHING2;
CREATE DATABASE CH12_FETCHING2;

DROP DATABASE IF EXISTS CH12_FETCHING3;
CREATE DATABASE CH12_FETCHING3;

DROP DATABASE IF EXISTS CH12_FETCHING4;
CREATE DATABASE CH12_FETCHING4;

DROP DATABASE IF EXISTS CH12_FETCHING5;
CREATE DATABASE CH12_FETCHING5;

DROP DATABASE IF EXISTS CH12_FETCHING6;
CREATE DATABASE CH12_FETCHING6;

DROP DATABASE IF EXISTS CH12_FETCHING7;
CREATE DATABASE CH12_FETCHING7;

DROP DATABASE IF EXISTS CH12_FETCHING8;
CREATE DATABASE CH12_FETCHING8;

DROP DATABASE IF EXISTS CH12_FETCHING8_1;
CREATE DATABASE CH12_FETCHING8_1;

DROP DATABASE IF EXISTS CH12_FETCHING8_2;
CREATE DATABASE CH12_FETCHING8_2;

DROP DATABASE IF EXISTS CH12_FETCHING9;
CREATE DATABASE CH12_FETCHING9;

DROP DATABASE IF EXISTS CH12_FETCHING10;
CREATE DATABASE CH12_FETCHING10;