DROP DATABASE IF EXISTS CH13_CASCADE;
CREATE DATABASE CH13_CASCADE;

DROP DATABASE IF EXISTS CH13_CALLBACK;
CREATE DATABASE CH13_CALLBACK;

DROP DATABASE IF EXISTS CH13_INTERCEPTOR;
CREATE DATABASE CH13_INTERCEPTOR;

DROP DATABASE IF EXISTS CH13_ENVERS;
CREATE DATABASE CH13_ENVERS;

DROP DATABASE IF EXISTS CH13_DYNAMIC;
CREATE DATABASE CH13_DYNAMIC;