DROP DATABASE IF EXISTS CH10_MANAGING_DATA;
CREATE DATABASE CH10_MANAGING_DATA;

DROP DATABASE IF EXISTS CH10_MANAGING_DATA_REPLICATE;
CREATE DATABASE CH10_MANAGING_DATA_REPLICATE;

DROP DATABASE IF EXISTS CH10_MANAGING_DATA2;
CREATE DATABASE CH10_MANAGING_DATA2;

