DROP DATABASE IF EXISTS CH15_SPRINGDATAJDBC;
CREATE DATABASE CH15_SPRINGDATAJDBC;

DROP DATABASE IF EXISTS CH15_SPRINGDATAJDBC2;
CREATE DATABASE CH15_SPRINGDATAJDBC2;

DROP DATABASE IF EXISTS CH15_SPRINGDATAJDBC3;
CREATE DATABASE CH15_SPRINGDATAJDBC3;

DROP DATABASE IF EXISTS CH15_SPRINGDATAJDBC4;
CREATE DATABASE CH15_SPRINGDATAJDBC4;

DROP DATABASE IF EXISTS CH15_SPRINGDATAJDBC5;
CREATE DATABASE CH15_SPRINGDATAJDBC5;

DROP DATABASE IF EXISTS CH15_SPRINGDATAJDBC6;
CREATE DATABASE CH15_SPRINGDATAJDBC6;