DROP DATABASE IF EXISTS CH05_GENERATOR;
DROP DATABASE IF EXISTS CH05_MAPPING;
DROP DATABASE IF EXISTS CH05_SUBSELECT;
CREATE DATABASE CH05_GENERATOR;
CREATE DATABASE CH05_MAPPING;
CREATE DATABASE CH05_SUBSELECT;