DROP DATABASE IF EXISTS CH11_TRANSACTIONS;
CREATE DATABASE CH11_TRANSACTIONS;

DROP DATABASE IF EXISTS CH11_TRANSACTIONS2;
CREATE DATABASE CH11_TRANSACTIONS2;

DROP DATABASE IF EXISTS CH11_TRANSACTIONS3;
CREATE DATABASE CH11_TRANSACTIONS3;

DROP DATABASE IF EXISTS CH11_TRANSACTIONS4;
CREATE DATABASE CH11_TRANSACTIONS4;

DROP DATABASE IF EXISTS CH11_TRANSACTIONS5;
CREATE DATABASE CH11_TRANSACTIONS5;